{
 "title": "Server-1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Node_Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cpu Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Uti",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemFree_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network_receive_bytes",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=\"eth0\", instance=\"172.31.45.37:9100\", job=\"server-1\"}",
     "legendFormat": "network_receive"
    }
   ]
  },
  {
   "title": "network_transmit_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{device=\"eth0\", instance=\"172.31.45.37:9100\", job=\"server-1\"}",
     "legendFormat": "network_transmit"
    }
   ]
  },
  {
   "title": "disk io",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_disk_io_now{device=\"xvda\", instance=\"172.31.45.37:9100\", job=\"server-1\"}",
     "legendFormat": "disk"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"172.31.45.37:9100\", job=\"server-1\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  { "title": "App_Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "reload_failure",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jmx_config_reload_failure_total{instance=\"172.31.45.37:12345\", job=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "thread state",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_threads_state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "jvm_threads_started_total{instance=\"172.31.45.37:12345\", job=\"app\"}",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\r\njava_lang_Memory_HeapMemoryUsage_used{instance=\"172.31.45.37:12345\", job=\"app\"}",
     "legendFormat": "HeapMemoryUsage"
    }
   ]
  }
 ]
}