---
- name: Install & configure Prometheus and Grafana
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Prerequisites
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Docker Install 
      apt:
        name: docker-ce
        state: present

    - name: APrometheus GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Prometheus repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present

    - name: Prometheus & Grafana
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - prometheus
        - grafana

    - name: Start Prometheus service
      service:
        name: prometheus
        state: started
        enabled: yes

    - name: Start Grafana service
      service:
        name: grafana-server
        state: started
        enabled: yes
