global:
  scrape_interval: 10s
scrape_configs:
   - job_name: 'Prometheus'
     scrape_interval: 5s
     static_configs:
         - targets: ['localhost:9090']
   - job_name: 'server-1'
     scrape_interval: 5s
     static_configs:
         - targets: ['172.31.45.37:9100']
   - job_name: 'app'
     scrape_interval: 5s
     static_configs:
         - targets: ['172.31.45.37:12345']
